### ISSUE TITLE
/sites/{siteid}/prices date ranges

### ISSUE THREAD

**Issue by CRCinAU** [amberelectric/public-api#16]
When I try to give a startDate or endDate, is this in NEM time or UTC?

I tried asking for what may have been an invalid time, but got back a whole heap of elements in an array - but certainly more than the 4 periods I asked for.

How do the date ranges interact with past / present information?

Is there a specific format to send them in? or will any ISO8601 string work?

**Comment by madpilot** [comment]
startDate and endDate are both in UTC, supplied in ISO 8601 date format ie `2021-05-03` (There is no validation on this yet, which is why it is "working" - if it can't parse the date correctly, it'll just return the current day - this will be fixed prior to public release)

The API will always return the whole day.

So `startDate=2021-05-03&endDate=2021-05-03` will return all 48 intervals for that day.

The rationale is to avoid subtle bugs due to NEM intervals being referenced by the end of the period. 

In the above example, the actual query is to find all intervals ending between `2021-05-03T00:30:00` and `2021-05-04T00:00:00` - We get stung by this bug internally all the time, so I can guarantee users without a strong knowledge of the NEW will get tripped up.

If you need less, you can filter client-side. If you need a rolling 24-hour window, pull the previous and next day too, then filter to the required range.

**Comment by CRCinAU** [comment]
Just so I understand, does that mean if I want to retrieve a full day for the AEST timezone, I need to pull two dates via UTC format and then create that via parsing the returned data?

**Comment by madpilot** [comment]
Sorry, I misspoke. startDate and endDate are NEM time, so for AEST you can just supply one day. For AESDT you'll need to pull two days worth of data to get the last two intervals.

**Comment by madpilot** [comment]
Note: the Usage view shows the days in NEM time, so during daylight savings, the first entry is 1am.

**Comment by CRCinAU** [comment]
Would it be possible in future to allow any ISO8601 string as a start / end date?

That way, we could do a single request with times included for all scenarios and just request via UTC time - or even the AEDT string to get the correct output no matter what.

**Comment by madpilot** [comment]
Going to throw this in the suggestions discussion thread

**Comment by rob0101** [comment]
If you want feedback on date formatting, my preference would be YYMMDDhhmm
Can be sorted as a number or string.

**Comment by madpilot** [comment]
ISO 8601 can be sorted lexicographically, too. It's one of the reason we chose it.

**Comment by rob0101** [comment]
Note for SA people. Pulling 2 days to get all the 30m blocks is not so simple.

Half the year you have to request the day you want plus the day before. The other half of the year you’ll need to request the day you want and the following day.  SA time alternates between -30m and +30m of NEM time due to daylight savings.

**Comment by madpilot** [comment]
Yeah, this is true.

For usage, I think we'll stick with the current system - It's what we do in the app already, and it maps to how people get billed (a billable day is NEM time).

I'm going to re-think the prices endpoint.
